services:
  - type: web
    name: car-damage-ocr
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run App.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11